### ISSUE TITLE
Remove multiple tags from multiple persons not working

### ISSUE THREAD

**Issue by RonakLakhotia** [CS2103AUG2017-T09-B4/main#101]
<img width="1275" alt="screen shot 2017-11-03 at 3 04 32 pm" src="https://user-images.githubusercontent.com/28557842/32363112-97426e7e-c0a8-11e7-851b-184ead56766f.png">

**Comment by NabeelZhr** [comment]
Hi! Thanks for your input.
Actually the command for removing tags is "removetag" or "rt" instead of "remove".
That's probably why it is stated as unknown command.

Maybe i could amend the user guide to make it clearer. Thanks!
