### ISSUE TITLE
Adding and Removing remarks from multiple indices seems to not work

### ISSUE THREAD

**Issue by raisa2010** [CS2103AUG2017-T09-B4/main#102]
Hello, it seems the suggested commands in the UG don't work for adding and removing remarks with multiple indices:

![image](https://user-images.githubusercontent.com/18502799/32363374-0ddf4ed4-c0aa-11e7-9df8-a73d084ae503.png)

![image](https://user-images.githubusercontent.com/18502799/32363335-dc85a22a-c0a9-11e7-8f0d-edfa244403f7.png)

![image](https://user-images.githubusercontent.com/18502799/32363354-f50d75f2-c0a9-11e7-9c87-00e92ce08b2e.png)

![image](https://user-images.githubusercontent.com/18502799/32363363-0248f9d0-c0aa-11e7-97eb-4115c32b1263.png)

Thank you!

**Comment by limyongsong** [comment]
Hi, thanks for reviewing the application.

But just to note the format for removeremark and removetag is different. Remark doesnt allow for for multiple remark addition/removal from multiple people at once (only 1 person at one time) [even though tags does allow that]

Sorry that the userguide might be a little confusing.
But based on your trial, maybe I should add that enhancement, so thanks again for the review.

-------------------------------------------------------------------------

Format to add tag: addtag TAG…​ INDEX…​
Format to remove tag: removetag TAG…​ INDEX…​

Format to add remark: addremark INDEX r/REMARK
Format to remove remark: removeremark INDEX REMARKINDEX

Note: INDEX means person index, REMARKINDEX is the remark index

**Comment by raisa2010** [comment]
Thank you for clarifying!
