### ISSUE TITLE
Adding Twitter Links from copied URL's

### ISSUE THREAD

**Issue by raisa2010** [CS2103AUG2017-T09-B4/main#103]
Hello!

Twitter links are usually copied from the browser in the following format:

![image](https://user-images.githubusercontent.com/18502799/32363469-822e2814-c0aa-11e7-935f-0aa9c980f5fe.png)

This doesn't work when pasting into the link command, and the "www." must either be added or the "https://" must be removed. I'm not sure if this distinct difference was intended but if so, it wasn't specified clearly enough in the UG.

Thank you!

**Comment by limyongsong** [comment]
Thanks for the review! 
I had wanted to add that, but seem to have forgotten. Thanks for letting me know.
